---
enable_ufw_firewall: true
reboot_box: false

install_packages:
  - autossh
  - curl
  - nfs-common
  - nmap
  - python3-dev
  - python3-pip
  - python3-venv
  - screen

masscan_install_packages:
  - git
  - gcc
  - libpcap-dev
  - make

# python
python_version: 3.8

# Python virtual environment.
engine_dir: /root/engine
venv_dir: "{{ engine_dir }}/.venv"
venv_python: "{{ venv_dir }}/bin/python{{ python_version }}"

# Additional nmap .nse script file URLs.  Will be saved in /usr/share/nmap/scripts/
nse_script_urls:
  - https://raw.githubusercontent.com/theMiddleBlue/nmap-elasticsearch-nse/master/elasticsearch.nse
